package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static huoltokirja.Apulaskut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.13 17:10:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ApulaskutTest {



  // Generated by ComTest BEGIN
  /** testOnkoSamat34 */
  @Test
  public void testOnkoSamat34() {    // Apulaskut: 34
    assertEquals("From: Apulaskut line: 35", true, onkoSamat("Matti Nykänen","    matti* ")); 
    assertEquals("From: Apulaskut line: 36", true, onkoSamat("Matti","Matti")); 
    assertEquals("From: Apulaskut line: 37", true, onkoSamat("Matti","matti")); 
    assertEquals("From: Apulaskut line: 38", false, onkoSamat("Matti","Katti")); 
  } // Generated by ComTest END
}