package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static huoltokirja.Apulaskut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.15 22:15:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ApulaskutTest {



  // Generated by ComTest BEGIN
  /** testOnkoSamat36 */
  @Test
  public void testOnkoSamat36() {    // Apulaskut: 36
    assertEquals("From: Apulaskut line: 37", true, onkoSamat("Matti Nykänen","    matti* ")); 
    assertEquals("From: Apulaskut line: 38", true, onkoSamat("Matti","Matti")); 
    assertEquals("From: Apulaskut line: 39", true, onkoSamat("Matti","matti")); 
    assertEquals("From: Apulaskut line: 40", false, onkoSamat("Matti","Katti")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKarkausvuosi87 */
  @Test
  public void testKarkausvuosi87() {    // Apulaskut: 87
    assertEquals("From: Apulaskut line: 88", 0, karkausvuosi(1900));
    assertEquals("From: Apulaskut line: 89", 0, karkausvuosi(1900));
    assertEquals("From: Apulaskut line: 90", 0, karkausvuosi(1901));
    assertEquals("From: Apulaskut line: 91", 1, karkausvuosi(1996));
    assertEquals("From: Apulaskut line: 92", 1, karkausvuosi(2000));
    assertEquals("From: Apulaskut line: 93", 0, karkausvuosi(2001));
    assertEquals("From: Apulaskut line: 94", 1, karkausvuosi(2004));
  } // Generated by ComTest END
}