package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static huoltokirja.Apulaskut.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 09:12:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ApulaskutTest {



  // Generated by ComTest BEGIN
  /** testOnkoSamat31 */
  @Test
  public void testOnkoSamat31() {    // Apulaskut: 31
    assertEquals("From: Apulaskut line: 32", true, onkoSamat("Matti Nykänen","    matti* ")); 
    assertEquals("From: Apulaskut line: 33", true, onkoSamat("Matti","Matti")); 
    assertEquals("From: Apulaskut line: 34", true, onkoSamat("Matti","matti")); 
    assertEquals("From: Apulaskut line: 35", false, onkoSamat("Matti","Katti")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoLaitonPvm52 */
  @Test
  public void testOnkoLaitonPvm52() {    // Apulaskut: 52
    assertEquals("From: Apulaskut line: 53", false, onkoLaitonPvm("1.1.2020")); 
    assertEquals("From: Apulaskut line: 54", false, onkoLaitonPvm("31.12.2020")); 
    assertEquals("From: Apulaskut line: 55", false, onkoLaitonPvm("29.2.2020")); 
    assertEquals("From: Apulaskut line: 56", true, onkoLaitonPvm("29.2.2021")); 
    assertEquals("From: Apulaskut line: 57", true, onkoLaitonPvm("30.2.2020")); 
    assertEquals("From: Apulaskut line: 58", false, onkoLaitonPvm("14.6.2020")); 
    assertEquals("From: Apulaskut line: 59", true, onkoLaitonPvm("30.2.1989"));  // ei hyväksytä ennen 2020 tehtyjä huoltoja.
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKarkausvuosi92 */
  @Test
  public void testKarkausvuosi92() {    // Apulaskut: 92
    assertEquals("From: Apulaskut line: 93", 0, karkausvuosi(1900));
    assertEquals("From: Apulaskut line: 94", 0, karkausvuosi(1900));
    assertEquals("From: Apulaskut line: 95", 0, karkausvuosi(1901));
    assertEquals("From: Apulaskut line: 96", 1, karkausvuosi(1996));
    assertEquals("From: Apulaskut line: 97", 1, karkausvuosi(2000));
    assertEquals("From: Apulaskut line: 98", 0, karkausvuosi(2001));
    assertEquals("From: Apulaskut line: 99", 1, karkausvuosi(2004));
  } // Generated by ComTest END
}