package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.08 20:03:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HuoltoTest {



  // Generated by ComTest BEGIN
  /** testToString85 */
  @Test
  public void testToString85() {    // Huolto: 85
    Huolto huolto1 = new Huolto(); 
    huolto1.parse(" 1  |  1  |  Jarruhuolto  | 75 | puhdistin ja vaihdoin"); 
    assertEquals("From: Huolto line: 88", "1|1|Jarruhuolto|75|puhdistin ja vaihdoin", huolto1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse106 */
  @Test
  public void testParse106() {    // Huolto: 106
    Huolto huolto2 = new Huolto(); 
    huolto2.parse(" 2  |  2  |  Iskari  | 100 | Öljynvaihto"); 
    assertEquals("From: Huolto line: 109", "Iskari", huolto2.getNimi()); 
    assertEquals("From: Huolto line: 110", 100, huolto2.getAjotunnit()); 
    assertEquals("From: Huolto line: 111", "2|2|Iskari|100|Öljynvaihto", huolto2.toString());
    assertEquals("From: Huolto line: 112", 2, huolto2.getTunnusNro()); 
    huolto2.rekisteroi();  // rekisteröinti kasvattaa tunnusNro arvoa yhdellä
    assertEquals("From: Huolto line: 114", 3, huolto2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi131 */
  @Test
  public void testRekisteroi131() {    // Huolto: 131
    Huolto huolto3 = new Huolto(); 
    huolto3.rekisteroi(); 
    assertEquals("From: Huolto line: 134", 4, huolto3.getTunnusNro());  // TunnusNro = 4, koska huolto 2 rekisteröitiin kahdesti.
    Huolto huolto4 = new Huolto(); 
    huolto4.rekisteroi(); 
    assertEquals("From: Huolto line: 137", 5, huolto4.getTunnusNro()); 
  } // Generated by ComTest END
}