package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.19 13:57:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PyoratTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws ApuException when error
   */
  @Test
  public void testLisaa45() throws ApuException {    // Pyorat: 45
    Pyorat pyorat = new Pyorat(); 
    Pyora pyora1 = new Pyora(), pyora2 = new Pyora(); Pyora pyora3 = new Pyora(); Pyora pyora4 = new Pyora(); Pyora pyora5 = new Pyora(); 
    assertEquals("From: Pyorat line: 49", 0, pyorat.getLkm()); 
    pyorat.lisaa(pyora1); assertEquals("From: Pyorat line: 50", 1, pyorat.getLkm()); 
    pyorat.lisaa(pyora2); assertEquals("From: Pyorat line: 51", 2, pyorat.getLkm()); 
    pyorat.lisaa(pyora3); assertEquals("From: Pyorat line: 52", 3, pyorat.getLkm()); 
    assertEquals("From: Pyorat line: 53", pyora1, pyorat.anna(0)); 
    assertEquals("From: Pyorat line: 54", pyora2, pyorat.anna(1)); 
    assertEquals("From: Pyorat line: 55", pyora3, pyorat.anna(2)); 
    try {
    assertEquals("From: Pyorat line: 56", pyora3, pyorat.anna(3)); 
    fail("Pyorat: 56 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: Pyorat line: 57", pyora3, pyorat.anna(-1)); 
    fail("Pyorat: 57 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pyorat.lisaa(pyora4); assertEquals("From: Pyorat line: 58", 4, pyorat.getLkm()); 
    pyorat.lisaa(pyora5); assertEquals("From: Pyorat line: 59", 5, pyorat.getLkm()); 
    try {
    pyorat.lisaa(pyora5); 
    fail("Pyorat: 60 Did not throw ApuException");
    } catch(ApuException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}