package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.18 14:24:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PyoraTest {



  // Generated by ComTest BEGIN
  /** testGetNimi44 */
  @Test
  public void testGetNimi44() {    // Pyora: 44
    Pyora pyora = new Pyora(); 
    assertEquals("From: Pyora line: 46", "", pyora.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi73 */
  @Test
  public void testRekisteroi73() {    // Pyora: 73
    Pyora pyora = new Pyora(); 
    pyora.rekisteroi(); 
    assertEquals("From: Pyora line: 76", 1, pyora.getTunnusNro()); 
    Pyora pyora2 = new Pyora(); 
    pyora2.rekisteroi(); 
    assertEquals("From: Pyora line: 79", 2, pyora2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString93 */
  @Test
  public void testToString93() {    // Pyora: 93
    Pyora pyora3 = new Pyora(); 
    pyora3.parse(" 3 |  Kottero  |  Helkama   | Jopo  | 2000   | abc123"); 
    assertEquals("From: Pyora line: 96", "3|Kottero|Helkama|Jopo|2000|abc123", pyora3.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse115 */
  @Test
  public void testParse115() {    // Pyora: 115
    Pyora pyora4 = new Pyora(); 
    pyora4.parse(" 4 |  Fuji Rakan  |  Fuji   | Rakan  | 2000   | abc123"); 
    assertEquals("From: Pyora line: 118", "Fuji Rakan", pyora4.getNimi()); 
    assertEquals("From: Pyora line: 119", "4|Fuji Rakan|Fuji|Rakan|2000|abc123", pyora4.toString());
    assertEquals("From: Pyora line: 120", 4, pyora4.getTunnusNro()); 
    pyora4.rekisteroi();  // rekisteröinti kasvattaa tunnusNro arvoa yhdellä
    assertEquals("From: Pyora line: 122", 5, pyora4.getTunnusNro()); 
  } // Generated by ComTest END
}