package huoltokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.30 15:33:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PyoraTest {



  // Generated by ComTest BEGIN
  /** testAseta96 */
  @Test
  public void testAseta96() {    // Pyora: 96
    Pyora pyora3 = new Pyora(); 
    assertEquals("From: Pyora line: 98", "Tunnusnumero on väärin", pyora3.aseta(0,"a")); 
    assertEquals("From: Pyora line: 99", null, pyora3.aseta(0,"3")); 
    assertEquals("From: Pyora line: 100", "vuosimalli on väärin", pyora3.aseta(4,"2008a")); 
    assertEquals("From: Pyora line: 101", null, pyora3.aseta(4,"2008")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi143 */
  @Test
  public void testGetNimi143() {    // Pyora: 143
    Pyora pyora1 = new Pyora(); 
    assertEquals("From: Pyora line: 145", "", pyora1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone156 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone156() throws CloneNotSupportedException {    // Pyora: 156
    Pyora pyora4 = new Pyora(); 
    pyora4.parse(" 4 |  Kottero  |  Helkama   | Jopo  | 2000   | abc123"); 
    Pyora kopio = pyora4.clone(); 
    pyora4.parse(" 4 |  Kaupunkipyörä  |  Helkama   | Jopo  | 2000   | abc123"); 
    assertEquals("From: Pyora line: 162", false, kopio.toString().equals(pyora4.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi192 */
  @Test
  public void testRekisteroi192() {    // Pyora: 192
    Pyora pyora6 = new Pyora(); 
    pyora6.rekisteroi(); 
    assertEquals("From: Pyora line: 195", 7, pyora6.getTunnusNro()); 
    Pyora pyora7 = new Pyora(); 
    pyora7.rekisteroi(); 
    assertEquals("From: Pyora line: 198", 8, pyora7.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString212 */
  @Test
  public void testToString212() {    // Pyora: 212
    Pyora pyora2 = new Pyora(); 
    pyora2.parse(" 2 |  Kottero  |  Helkama   | Jopo  | 2000   | abc123"); 
    assertEquals("From: Pyora line: 215", "2|Kottero|Helkama|Jopo|2000|abc123", pyora2.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse234 */
  @Test
  public void testParse234() {    // Pyora: 234
    Pyora pyora5 = new Pyora(); 
    pyora5.parse(" 5 |  Fuji Rakan  |  Fuji   | Rakan  | 2000   | abc123"); 
    assertEquals("From: Pyora line: 237", "Fuji Rakan", pyora5.getNimi()); 
    assertEquals("From: Pyora line: 238", "5|Fuji Rakan|Fuji|Rakan|2000|abc123", pyora5.toString());
    assertEquals("From: Pyora line: 239", 5, pyora5.getTunnusNro()); 
    pyora5.rekisteroi();  // rekisteröinti kasvattaa tunnusNro arvoa yhdellä
    assertEquals("From: Pyora line: 241", 6, pyora5.getTunnusNro()); 
  } // Generated by ComTest END
}