package huoltokirja.test;
// Generated by ComTest BEGIN
import huoltokirja.Pyora;
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.09 21:00:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt14 */
  @Test
  public void testInt14() {    // Tietue: 14
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 17", 6, pyora.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt25 */
  @Test
  public void testInt25() {    // Tietue: 25
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 27", 1, pyora.ekaKentta()); 
    Huolto huolto = new Huolto(); 
    assertEquals("From: Tietue line: 29", 2, huolto.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt38 */
  @Test
  public void testInt38() {    // Tietue: 38
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 40", 7, pyora.ekaIsoKentta()); 
    Huolto huolto = new Huolto(); 
    assertEquals("From: Tietue line: 42", 4, huolto.ekaIsoKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString53 */
  @Test
  public void testString53() {    // Tietue: 53
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 55", "Nimi", pyora.getKentanNimi(1)); 
    assertEquals("From: Tietue line: 56", "Merkki", pyora.getKentanNimi(2)); 
    assertEquals("From: Tietue line: 57", "Malli", pyora.getKentanNimi(3)); 
    assertEquals("From: Tietue line: 58", "Vuosimalli", pyora.getKentanNimi(4)); 
    assertEquals("From: Tietue line: 59", "Runkonumero", pyora.getKentanNimi(5)); 
    Huolto huolto = new Huolto(); 
    assertEquals("From: Tietue line: 61", "Nimi", huolto.getKentanNimi(2)); 
    assertEquals("From: Tietue line: 62", "Ajotunnit", huolto.getKentanNimi(3)); 
    assertEquals("From: Tietue line: 63", "Toimenpiteet", huolto.getKentanNimi(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString75 */
  @Test
  public void testString75() {    // Tietue: 75
    Pyora pyora = new Pyora(); 
    pyora.parse(" 3 |  Fuji Rakan  |  Fuji   | Rakan  | 2000   | abc123"); 
    assertEquals("From: Tietue line: 78", "Fuji Rakan", pyora.anna(1)); 
    assertEquals("From: Tietue line: 79", "Fuji", pyora.anna(2)); 
    assertEquals("From: Tietue line: 80", "Rakan", pyora.anna(3)); 
    assertEquals("From: Tietue line: 81", "2000", pyora.anna(4)); 
    assertEquals("From: Tietue line: 82", "abc123", pyora.anna(5)); 
    Huolto huolto = new Huolto(); 
    huolto.parse(" 2  |  2  |  Iskari  | 100 | Öljynvaihto"); 
    assertEquals("From: Tietue line: 85", "Iskari", huolto.anna(2)); 
    assertEquals("From: Tietue line: 86", "100", huolto.anna(3)); 
    assertEquals("From: Tietue line: 87", "Öljynvaihto", huolto.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString99 */
  @Test
  public void testString99() {    // Tietue: 99
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 101", null, pyora.aseta(1, "hybridi")); 
    assertEquals("From: Tietue line: 102", "hybridi", pyora.anna(1)); 
    assertEquals("From: Tietue line: 103", "vuosimalli on väärin", pyora.aseta(4, "2005s")); 
    assertEquals("From: Tietue line: 104", "0", pyora.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString123 */
  @Test
  public void testToString123() {    // Tietue: 123
    Pyora pyora2 = new Pyora(); 
    pyora2.parse(" 2 |  Kottero  |  Helkama   | Jopo  | 2000   | abc123"); 
    assertEquals("From: Tietue line: 126", "2|Kottero|Helkama|Jopo|2000|abc123", pyora2.toString());
  } // Generated by ComTest END
}