package huoltokirja.test;
// Generated by ComTest BEGIN
import huoltokirja.Pyora;
import static org.junit.Assert.*;
import org.junit.*;
import huoltokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.31 12:23:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt17 */
  @Test
  public void testInt17() {    // Tietue: 17
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 20", 6, pyora.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt28 */
  @Test
  public void testInt28() {    // Tietue: 28
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 30", 1, pyora.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString41 */
  @Test
  public void testString41() {    // Tietue: 41
    Pyora pyora = new Pyora(); 
    assertEquals("From: Tietue line: 43", "Nimi", pyora.getKentanNimi(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString81 */
  @Test
  public void testToString81() {    // Tietue: 81
    Pyora pyora2 = new Pyora(); 
    pyora2.parse(" 2 |  Kottero  |  Helkama   | Jopo  | 2000   | abc123"); 
    assertEquals("From: Tietue line: 84", "2|Kottero|Helkama|Jopo|2000|abc123", pyora2.toString());
  } // Generated by ComTest END
}